version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
    - 5672:5672
    - 15672:15672

  server:
    build: .
    depends_on:
      - rabbitmq
    volumes:
      - .:/dir
    ports:
      - 5000:5000
    

